spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro-user
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081