spring:
  zipkin:
    base-url: http://localhost:9411/zipkin/
  datasource:
    url: jdbc:postgresql://localhost:5432/api-db-test
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  application:
    name: fraud
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true